name: Django Projec DCI Example
on:
    push:
        branches: [main]

    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Django Project for Django Project DCI Example
            - uses: actions/checkout@v2

            - name: Set up Python 3.8
                uses: actions/setup-python@v2
                with:
                    python-version: 3.8

            - name: Install Dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Test with unittest
                run: |
                make dev-test2
                